global:
  scrape_interval: 30s
scrape_configs:
  - job_name: 'app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['https://prometheus-flask-vedant-a9dsccdhcrdxa2c6.centralus-01.azurewebsites.net']