global:
  scrape_interval: 30s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']  # Local Alertmanager

scrape_configs:
  - job_name: 'app'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets:
          - 'prometheus-flask-vedant-a9dsccdhcrdxa2c6.centralus-01.azurewebsites.net:443'
